### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by ewjoachim**
Anyone with review access, please merge it :) Tag has already been pushed, and release on PyPI was already made.

### CODE REVIEW

**Comment by pilou-** [comment]
Changelog doesn't mention that Python 3.5 (which is provided by Debian stable) isn't supported anymore (#54).

**Comment by ewjoachim** [comment]
@pilou- 
Interestingly enough, here's the related diff.

Note that `setup.cfg` (& thus packaging) wrongly stated that py3.5 was supported before and it was *not* the case.

I fully admint, though, that the dropping of py2.7 should have been documented in this changelog and py3.5 should never have been presented as supported if it was not the case.

```diff
diff --git a/tox.ini b/tox.ini
index 820ea12..d015feb 100644
--- a/tox.ini
+++ b/tox.ini
@@ -1,6 +1,6 @@
 [tox]
 envlist =
-    {py27,py36}-{integration,unit}-tests,check-lint
+    {py36,py37}-{integration,unit}-tests,check-lint

 diff --git a/.travis.yml b/.travis.yml
index a0d05ef..19e3f51 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,11 +15,15 @@ matrix:
   - python: 3.6
     env: TOX_ENV=py36-integration-tests COVERAGE_FLAG=integration
 
-  - python: 2.7
-    env: TOX_ENV=py27-unit-tests COVERAGE_FLAG=unit
+  - python: 3.7
+    env: TOX_ENV=py37-unit-tests COVERAGE_FLAG=unit
+
+  - python: 3.7
+    env: TOX_ENV=py37-integration-tests COVERAGE_FLAG=integration
+
+  - python: 3.7
+    env: TOX_ENV=check-lint
 
-  - python: 2.7
-    env: TOX_ENV=py27-integration-tests COVERAGE_FLAG=integration

diff --git a/setup.cfg b/setup.cfg
index ae9cfaf..618759f 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,7 +1,7 @@
 [metadata]
 name = vault-cli
 description = CLI tool for hashicorp vault
-version = 0.3.9
+version = 0.4.0
 author = ylachiver
 author_email = yann.lachiver@people-doc.com
 url = https://github.com/peopledoc/vault-cli
@@ -13,9 +13,11 @@ classifiers =
     Development Status :: 4 - Beta
     Intended Audience :: Developers
     License :: OSI Approved :: Apache Software License
+    Programming Language :: Python :: 2
+    Programming Language :: Python :: 2.7
     Programming Language :: Python :: 3
-    Programming Language :: Python :: 3.5
     Programming Language :: Python :: 3.6
+    Programming Language :: Python :: 3.7
```

**Comment by ewjoachim** [comment]
@pilou- I've added the relevant part in the changelog. Note that they cannot be retroactively added into the 0.4.0 but we could add them in a 0.4.1 that's juste for proper packaging. You tell me :)

**Comment by pilou-** [comment]
> Note that they cannot be retroactively added into the 0.4.0 but we could add them in a 0.4.1 that's just for proper packaging.

A new release with these changes only doesn't seem required, a new release will be without effect/consequence.

Should not support for Python 2.7 be removed from `setup.cfg` ? Should not `vault-cli` wheel package Python version mention `py3` instead of `py2.py3` ?

Note that `vault-cli` 0.3.9 is officially working well with Python 3.5 ;)

**Comment by ewjoachim** [comment]
> A new release with these changes only doesn't seem required, a new release will be without effect/consequence.

:+1: 

> Should not support for Python 2.7 be removed from setup.cfg ?

Whoaw I hadn't realized it was there ! Thank you fixing that ! (and this time, a new release will have an effect)

> Should not vault-cli wheel package Python version mention py3 instead of py2.py3 ?

Yep. Never done that though. I'll try to see how it's done.

> Note that vault-cli 0.3.9 is officially working well with Python 3.5 ;)

It's working, I don't doubt that, but not officially :D 

And again, sorry about the mess, I screwed up communication regarding this.

**Comment by ewjoachim** [comment]
@pilou- done. Now 0.4.1, the .0 is always cursed anyway.

**Comment by ewjoachim** [comment]
Ping @pilou-

**Pull request merged**
