### PR TITLE
Do not see ssh-add message

### LINKED ISSUE #167: [Vault_cli][SSH] ssh-add message
Bonjour à tous, 

lors de l'utilisation de vault_cli avec l'option ssh, le message de ssh-add s'affiche.

```
/usr/local/bin/vault --config-file /etc/{SERVICE}/vault_ro.yml ssh --key {PATH}:{VALUE}

Identity added: (stdin) ((stdin))
```

Est-il possible de rendre cette affichage optionnel afin de pouvoir le désactiver (notamment lors de l'utilisation via cron) ?

### PR DESCRIPTION
**Pull request by jybeepeopledoc**
Closes #167

Note : l'option -q est disponible à partir de OpenSSH_7.9p1

### Check list:
- [x] Write documentation (we can help you doing so)
- [x] Write unit tests (100% coverage ?)
- [x] Write or edit integration tests, if applicable ?
- [x] Add a line in ``CHANGELOG.rst``

### CODE REVIEW

**Comment by ewjoachim** [comment]
Hi ! Thanks for your contribution !

Let me know if you would rather:
- Finish it (write missing tests)
- Have us finish it for you
- Finish it with us

**Comment by elemoine** [comment]
Does this mean that, if the ssh command fails for some reason, vault_cli won't output any error message?

**Comment by ewjoachim** [comment]
Possible, though I doubt it. We check the exit code of ssh-add, so if it's not 0, we'll have an exception, and I believe (though we can test it) this exception includes stdout and stderr by default.

**Comment by ewjoachim** [comment]
After check : we don't check the returncode of that command :( which means even if it fails we happily go on.

I'll improve this on this PR.

**Comment by ewjoachim** [comment]
Fone, ready for review

**Comment by ewjoachim** [comment]
Congratulations @jybeepeopledoc for your first open source PR :tada: :+1: :sparkles:

**Comment by jybeepeopledoc** [comment]
Yeah victory !!!!!!! :D 
Thx guys ;)

**Pull request merged**
