### PR TITLE
initial refactoring

### PR DESCRIPTION
**Pull request by weakcamel**
push the file read/open operation down to template rendering functions

Cf. #113 

### Check list:
- [ ] Write unit tests (100% coverage ?)
- [ ] Write or edit integration tests, if applicable ?
- [ ] Add a line in CHANGELOG.md

### CODE REVIEW

**Comment by weakcamel** [comment]
@ewjoachim  This PR is just a draft to verify an option.

It appears to me that to properly use jinja2.FileSystemLoader, I'll need to push the file opening operations down to the `render_template()` or so.

This seems to be affecting a lot of unit tests; they pass the template as verbatim string (not a reference to file).

Just wanted to check with you if this seems a good direction for you.

**Comment by ewjoachim** [comment]
Hmm, I'm not entirely sold. The `cli` module should manage all of the command-line specific stuff (like the idea of `-` and the whole concept of stdin). The `client` module can be used as a vault library so it's expected that you can do, in your code:
```
import vault_cli
client = vault_cli.get_client()
client.render_template("something")
``` 
In this context, `calling render_template("-")` makes little sense.

> It appears to me that to properly use jinja2.FileSystemLoader, I'll need to push the file opening operations down to the render_template() or so.

I'd like to challenge this assumption with you, and see if we could find a way to use a loader that would accept string templates, but that would also accept the use of `include`. Maybe we'll need some kind of special loader...

**Comment by weakcamel** [comment]
I see what you mean.
Perhaps the other PR https://github.com/peopledoc/vault-cli/pull/115 (with modifications) would be a better start then?

**Comment by weakcamel** [comment]
Closing as final solution was merged under https://github.com/peopledoc/vault-cli/pull/116

**Pull request closed without merging**
