### PR TITLE
Certificate auth

### LINKED ISSUE #3: Authenticate using certificate

### PR DESCRIPTION
**Pull request by ewjoachim**
For now, I cannot test the functionnality: a vault launched with -dev is very practical and all, but has TLS disabled, and client cert needs tls enabled, which means we have to reconfigure our whole dev vault server without -dev, and I'm struggling. Any help ?

Closes #3

### CODE REVIEW

**Comment by pilou-** [comment]
@ewjoachim there is an example in [ansible integration test](https://github.com/ansible/ansible/blob/devel/test/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml): [`dev` mode is used](https://github.com/ansible/ansible/blob/e0f6c17857d6a5758fbe5e2018ab897b76784dbc/test/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml#L75) with [SSL authentication](https://github.com/ansible/ansible/blob/devel/test/integration/targets/lookup_hashi_vault/lookup_hashi_vault/templates/vault_config.hcl.j2).

**Comment by ewjoachim** [comment]
Oh, cool !

**Comment by ewjoachim** [comment]
Well, tried again and... I think I managed to setup the TLS server, and to setup a certificate that's ok, but I still can't manage to achieve cert login.

I give up, whoever wants to pick up where I left...

**Comment by ewjoachim** [comment]
Ready for review !

**Comment by ewjoachim** [comment]
@mgu Per your instructions, merging now (you can review a-posteriori)

**Pull request merged**
