### PR TITLE
Add support for secrets not stored in a "value" key

### PR DESCRIPTION
**Pull request by mgu**
Cf. #97 

vault-cli has been designed read and write all the values in a "value" key.
Here, if the secret does not contain a single "value" key, we return
directly the whole kv dict.

### Check list:
- [x] Write unit tests (100% coverage ?)
- [x] Write or edit integration tests, if applicable ?
- [x] Add a line in CHANGELOG.md

### CODE REVIEW

**Comment by mgu** [comment]
The goal is not to change the behavior of vault-cli, only to support data written by external sources.
I think we need to work on this "value" limitation in the future and then add some documentation about it.
But right now it's just a "quick but not so dirty" workaround

**Comment by PierreDucroquet** [comment]
For safety purpose the DBA team will have to switch to this kind of credential structure, so you will be able to test soon.

**Comment by PierreDucroquet** [comment]
You can see in qualif for the following cred: /case/database/cron/case_rw
It contains:
```
{'password': 'cassetoitupues',
'user': 'casecron_20190711',
'dsn': 'postgres://casecron_20190711:etmarchealombre@db-cairo.qualif.people-doc.net:5432/case_rw',
'host': 'db-cairo.qualif.people-doc.net',
'dbname': 'case_rw',
'port': 5432}
```

**Comment by brunobord** [comment]
well, by _testing_ I meant "testing write and read of this kind of structure on my local environment, using vault-cli, just for fun and to figure out how we can use it on 'true' environments"

**Comment by mgu** [comment]
I've added an integration test that uses hvac to push values without the "value" attribute.

**Comment by mgu** [comment]
in my mind, this will ease future evolutions if we want to remove the hard-coded "value" key

**Comment by ewjoachim** [comment]
ok then :)

**Pull request merged**
