### PR TITLE
Add `vault ln` and `--follow` features in client and cli

### LINKED ISSUE #65: Feature request - follow path
The vault-cli handles "special" secrets as a "path" to read.

For example, the vault-cli behavior expected would be:

* get the secret value `rabbitmq-front/creds/shared` from the path `app/infra/rabbit/front-shared/engine_path`
* read and return the secret value from this path `rabbitmq-front/creds/shared` (in this example the secret value is a json dict `{"username": "xx", "password": "xx"}`

ie. naive implementation: this behavior occurs when a path matches `/engine_path$`

This is needed to integrate RabbitMQ secret Engine 'seamlessly' for apps (https://www.vaultproject.io/docs/secrets/rabbitmq/index.html) 

cc @mgu @yannlachiver @pilou- @marieluce-allee @ccouturi @damienbertau

### PR DESCRIPTION
**Pull request by ewjoachim**
Closes #65 

### Check list:
- [x] Write unit tests (100% coverage ?)
- [x] Write or edit integration tests, if applicable ?
- [x] Add a line in CHANGELOG.md

### CODE REVIEW

**Comment by ewjoachim** [comment]
I'm kind of lost in terms of who I should ping so, interested parties, please follow the repo.

**Comment by ewjoachim** [comment]
Yes, the idea is that RabbitMQ can use Vault as the source of truth for the credentials definitions, but in order to do so, it needs the passwords to be written at a very specific place, and it would be nicer if the password could also live in the app "subfolder", without duplication. This means we want to have a way to alias the same password at 2 paths.

That being said, we're thinking about an alternative strategy where the "alias mapping" would be part of the client configuration and we wouldn't be writing things on the server for that, so maybe 90% of this PR will go to :recycle:

**Comment by pmourlanne** [comment]
Things are clear now, thanks :+1:

**Comment by ewjoachim** [comment]
Superseeded by #80

**Pull request closed without merging**
